apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka
    statefulset.kubernetes.io/pod-name: kafka-2
  name: kafka-2
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 9093
    protocol: TCP
    targetPort: 9093
  selector:
    app: kafka
    statefulset.kubernetes.io/pod-name: kafka-2
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
