apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"kafka","namespace":"default"},"spec":{"ports":[{"name":"broker","port":9092,"protocol":"TCP","targetPort":9092}],"selector":{"app":"kafka"},"type":"LoadBalancer"}}
  creationTimestamp: null
  name: kafka
  selfLink: /api/v1/namespaces/default/services/kafka
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: broker
    nodePort: 30502
    port: 9093
    protocol: TCP
    targetPort: 9093
  selector:
    app: kafka
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
