apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spark-master
spec:
  selector:
    matchLabels:
      app: spark-master
  serviceName: spark-master
  replicas: 2
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
      - name: spark-master
        image: bde2020/spark-master:2.4.4-hadoop2.7
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        - containerPort: 7077
        env:
        - name: SPARK_DAEMON_JAVA_OPTS
          value: "-Dspark.deploy.recoveryMode=ZOOKEEPER -Dspark.deploy.zookeeper.url=kafka-zookeeper-0.kafka-zookeeper-headless.default.svc.cluster.local:2181,kafka-zookeeper-1.kafka-zookeeper-headless.default.svc.cluster.local:2181,kafka-zookeeper-2.kafka-zookeeper-headless.default.svc.cluster.local:2181 -Dspark.deploy.zookeeper.dir=/sparkha"
