---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: spark-worker
  labels:
    app: spark-worker
spec:
  selector:
    matchLabels:
      name: spark-worker
  template:
    metadata:
      labels:
        name: spark-worker
    spec:
      containers:
      - name: spark-worker
        image: bde2020/spark-worker:2.4.4-hadoop2.7
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
        - name: SPARK_MASTER
          value: "spark://spark-master-0.spark-master.default.svc.cluster.local:7077,spark-master-1.spark-master.default.svc.cluster.local:7077"
        - name: SPARK_WORKER_CORES
          value: "2"
